---
name: Plan/Test on Workflow Run

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
    tags:
      description: 'Test scenario tags'
      required: false
      type: boolean
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true

jobs:
  log-the-inputs:
    runs-on: macos-latest
    steps:
      - run: |
          echo "Log Level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}

